### ISSUE TITLE
objc_getAssociatedObject always returns nil

### ISSUE THREAD

**Issue by ammerzon** [BayPhillips/draggable-swift#1]
I am using your great library for a while now but since today I always get nil when calling objc_getAssociatedObject (Command Line Tools: Xcode 7.3).

I use the extension in this way:
<img width="446" alt="bildschirmfoto 2016-04-18 um 09 37 33" src="https://cloud.githubusercontent.com/assets/7319168/14596850/6624bb7e-0549-11e6-9099-9002a1dada26.png">

**Comment by encaps** [comment]
Hi there,

same here...all of a sudden this does not work anymore....any ideas how to fix this?

Thanks a lot!

**Comment by BayPhillips** [comment]
I wonder if they changed something with the newest version of Swift? Anything in release notes?

**Comment by BayPhillips** [comment]
Looks like we might need to change the `objc_AssociationPolicy`? http://stackoverflow.com/a/25428013

**Comment by encaps** [comment]
setting the to `objc_AssociationPolicy`  to `OBJC_ASSOCIATION_RETAIN` doesn't seem to work....

**Comment by ammerzon** [comment]
I have also tried to change the policy to `OBJC_ASSOCIATION_RETAIN` but is does not work

**Comment by BayPhillips** [comment]
Hey @encaps @ammerzon , take a look at #2 . This "fixes" the issue, but I don't know why it isn't working anymore as I couldn't find any public change logs about it from Apple. Maybe something was updated unknowingly?

**Comment by encaps** [comment]
@BayPhillips , that fixes it for me!! Thanks a lot, I wasn't able to fix it myself....

**Comment by ammerzon** [comment]
@BayPhillips, thank you. #2 solved the problem.
